version = 0.1

[default.deploy.parameters]
stack_name = "f1racesim"
resolve_s3 = true
s3_prefix = "f1racesim"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
